# Generated by Django 4.1.5 on 2023-01-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSequences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(db_index=True, max_length=256)),
                ('protein_sequence', models.CharField(max_length=40000)),
            ],
        ),
        migrations.CreateModel(
            name='PfamDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pfam_id', models.CharField(db_index=True, max_length=20)),
                ('ogranism_scientific_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_id', models.CharField(db_index=True, max_length=20)),
                ('taxa_id', models.IntegerField(db_index=True)),
                ('clade_identifier', models.CharField(default='E', max_length=1)),
                ('scientific_name', models.CharField(max_length=256)),
                ('domain_description', models.CharField(max_length=256)),
                ('domain_id', models.CharField(db_index=True, max_length=20)),
                ('domain_start', models.IntegerField(blank=True)),
                ('domain_stop', models.IntegerField(blank=True)),
                ('length_protein', models.IntegerField(blank=True)),
            ],
        ),
    ]
