# Generated by Django 4.1.5 on 2023-01-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genedata', '0004_datasequences_pfamdescription_protein_remove_gene_ec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='taxa_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
